# Dockerfile para ENTORNO DE DESARROLLO

FROM python:3.11-slim

# Instalar dependencias del sistema operativo, incluyendo postgresql-client
RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copiar archivos de dependencias
COPY ./requirements.txt .
COPY ./requirements-dev.txt .

# Instalar dependencias
RUN pip install --no-cache-dir --upgrade -r requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements-dev.txt

# Copiar TODO el código fuente
# Esto asegura que 'scripts/wait-for-postgres.sh' está presente
COPY . .

# Dar permisos de ejecución al script de espera
RUN chmod +x /app/scripts/wait-for-postgres.sh

# El COMANDO se ejecuta desde docker-compose.dev.yml